name: mobile_assessment_jan_2025
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.2
  dio: ^5.7.0
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

assets:
  - assets/mockdata.json

flutter:
  uses-material-design: true
